### ISSUE TITLE
Are exports/imports supported?

### ISSUE THREAD

**Issue by jcoyne** [TannerRogalsky/sprockets-es6#11]
I have:

```es6
// cow.es6

export default class {
  moo() {
    console.log("moooooo!");
  }
};
```

it compiles to this js:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
// ...
```

and I get the error: `ReferenceError: exports is not defined` on line 3.  Any ideas?

**Comment by jcoyne** [comment]
It appears that babel is set to commonjs format for modules, which doesn't work in the browser.  Can we switch that to AMD?

**Comment by jcoyne** [comment]
Actually, for now, ignore might be the simplest. Certainly better than broken.

**Comment by jcoyne** [comment]
Not sure what you'd want to do here @TannerRogalsky It looks like you already have some module code in: https://github.com/TannerRogalsky/sprockets-es6/blob/7fb29910f68ea350fa1f0b49ddd05e0bdab9703c/lib/sprockets/es6.rb#L38-L40  But it's unclear how this is useful without setting the `modules` option.

**Comment by jcoyne** [comment]
I see this has been ported into rails/sprockets.  And I found the solution I needed:
https://github.com/rails/sprockets/issues/73#issuecomment-139113466

**Comment by TannerRogalsky** [comment]
@jcoyne, Glad you got it working to your liking. For my part, I use this to add module support. https://github.com/TannerRogalsky/sprockets-commonjs
