### ISSUE TITLE
cannot compile es6 file if it references plain .js file

### ISSUE THREAD

**Issue by Valve** [TannerRogalsky/sprockets-es6#13]
the error is: Sprockets::FileNotFound: couldn't find file '../vendor/routie.min' under '/tmp/build_dc3be3e29647996be2e1023ce463c5a6/app/assets/javascripts' with type 'text/ecmascript-6'

This file does exist, it just has .js extension

**Comment by Valve** [comment]
https://github.com/TannerRogalsky/sprockets-es6/pull/14 should fix it

**Comment by TannerRogalsky** [comment]
I'm afraid I don't full understand the issue. Would you consider writing a test case for this issue?
